name: Deploy frontend to S3 (mirror)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET: polly-bucket-edumgt
  BUILD_DIR: frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::086015456585:role/github-actions-ai-aws-polly-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Debug - list lambdas
        run: |
          aws lambda list-functions \
            --region "${{ env.AWS_REGION }}" \
            --query "Functions[?contains(FunctionName, 'polly')].FunctionName" \
            --output table


      - name: Deploy backend Lambda (zip upload only)
        shell: bash
        run: |
          chmod +x infra/aws-cli-dep2.sh
          AWS_REGION="${{ env.AWS_REGION }}" \
          LAMBDA_NAME="polly-tts-lambda" \
          LAMBDA_DIR="lambda" \
          ZIP_FILE="lambda.zip" \
          FAIL_IF_MISSING="1" \
          UPDATE_CONFIG="0" \
          ./infra/aws-cli-dep2.sh


      - name: Sync assets to S3 (mirror)
        run: |
          aws s3 sync "${{ env.BUILD_DIR }}/" "s3://${{ env.S3_BUCKET }}/frontend/" \
            --delete \
            --only-show-errors
